CREATE TABLE USER_M (
  USER_ID VARCHAR(30) PRIMARY KEY,
  USER_NAME VARCHAR(20) NOT NULL
);

INSERT INTO USER_M VALUES('chanwook', '박찬욱');
INSERT INTO USER_M VALUES('seojin', '박서진');
INSERT INTO USER_M VALUES('woojin', '박우진');