CREATE TABLE USER {
  USER_ID VARCHAR(30) PRIMARY KEY,
  USER_NAME VARCHAR(20) NOT NULL
};

INSERT INTO USER VALUES('chanwook', '박찬욱');
INSERT INTO USER VALUES('seojin', '박서진');
INSERT INTO USER VALUES('woojin', '박우진');